### PR TITLE
feat: Mod

### PR DESCRIPTION
**Pull request by JohnMasoner**

### CODE REVIEW

**Comment by JohnMasoner** [comment]
Hey, @senysenyseny16 ,

i add the new feature "Mod".

The torch has `torch.fmod` and `torch.remainder`, the `torch.fmod`  applies C++’s std::fmod entrywise,  `torch.remainder` computes Python’s modulus operation entrywise.

To ensure code uniformity, i use the `torch.remainder`.

**Comment by senysenyseny16** [comment]
Hi, @JohnMasoner 

Thanks for you contribution, but why are you close PR?

**Review by senysenyseny16 — CHANGES_REQUESTED** [review]
Could you please add tests for implemented op?

`tests/node_converters/binary_operations_tests.py`

**Comment by JohnMasoner** [comment]
@senysenyseny16 ,

My mistake caused me to close this PR.

i will add tests for operations.

**Comment by senysenyseny16** [comment]
Also, please take a look at this code

> @senysenyseny16 ,
> 
> My mistake caused me to close this PR.
> 
> i will add tests for operations.

Also, please take a look at this module: `onnx2torch/node_converters/binary_math_operations.py`.

**Comment by JohnMasoner** [comment]
Hey, @senysenyseny16 

It seems that I don't have permission to commit again because of my incorrect action.

**Pull request closed without merging**
